### ISSUE TITLE
Unknown device family camera

### ISSUE THREAD

**Issue by cap60552** [arraylabs/pymyq#104]
We recently replaced out garage door opener with one that has myq integrated.  The new opener also includes a camera.  When I switched over to the new device I now see errors:
[pymyq.api] Unknown device family camera

Is there anything I can do to help provide support for the camera?

**Comment by ehendrix23** [comment]
The API from MyQ is not openly published, so not knowing what needs to be done to support it makes difficult to figure it out. Someone who has a camera and is able to reverse engineer the API calls would need to come up with it and only then would there be a chance to support it.
