### ISSUE TITLE
Status not updating if closing interrupted 

### ISSUE THREAD

**Issue by broyuken** [arraylabs/pymyq#107]
If I click the button to close the door in HA, but due to a server error or the request timing out and never getting to the door, it will show in HA as “closing” forever. If I go into the MyQ app it will show as open, but HA shows closing. If I close the door through myQ or with the button, HA will update and show the correct status of closed. 

This also happens if the door is set to close, and break the beam causing it to go back up.

**Comment by broyuken** [comment]
Is this something that could be resolved? Or would I need to move to the home bridge?

**Comment by ehendrix23** [comment]
Can you try out the custom HACS component. It is the same as the one in HASS but uses latest beta version of myq. 

Install HACS custom component (if not already there) and then deploy the component using following link:
https://github.com/ehendrix23/hass_myq

**Comment by broyuken** [comment]
I moved to the home bridge but this should stay open as it’s a pretty huge issue. Once the door goes into that stage it won’t update again until I either close it via the myq app or via the wall button.

**Comment by ehendrix23** [comment]
Updating state within HASS if it fails to open/close is now added. So this issue should be fixed.

**Comment by broyuken** [comment]
awesome, I'll have a buddy check who uses the myq integration.

**Comment by ehendrix23** [comment]
Fixes should be going into next HASS release so would need to wait until it is released and your buddy upgraded then. 
PR is: https://github.com/home-assistant/core/pull/54724

**Comment by broyuken** [comment]
cool, thank you
