### ISSUE TITLE
Error when trying to open Garage Door

### ISSUE THREAD

**Issue by bbraden** [arraylabs/pymyq#129]
Hello, im running example.py, it logs in and everything, however. i keep getting this error when it trys to open the garage door: `ERROR:root:Error when trying to open Double Garage Door: Error requesting data from https://account-devices-gdo.myq-cloud.com/api/v5.2/Accounts/4eb17803-85d6-425d-8db0-6c0840b77b74/door_openers/CG0860A5D781/open: 403 - Forbidden` help?

**Comment by ehendrix23** [comment]
Make sure you have an actual MyQ account.
