### ISSUE TITLE
SSLCertVerificationError

### ISSUE THREAD

**Issue by FlyingDiver** [arraylabs/pymyq#141]
Using the example code as provided, with correct email and password:

```
ERROR:pymyq.api:Authentication failed: Error requesting data from https://partner-identity.myq-cloud.com/connect/authorize: Cannot connect to host partner-identity.myq-cloud.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')]
ERROR:root:There was an error: Error requesting data from https://partner-identity.myq-cloud.com/connect/authorize: Cannot connect to host partner-identity.myq-cloud.com:443 ssl:True [SSLCertVerificationError:
```

**Comment by ehendrix23** [comment]
Make sure your system has required certificates. For example, on a Mac after installing Python there is a script to be run to install certificates which can be found in Applications/Python xx folder.

**Comment by FlyingDiver** [comment]
OK, that was the problem.  I missed the script.  I'm not getting that error anymore, but it's saying invalid username/password, even though I know I'm using exactly what I use on myq.com.  Is that the correct website to verify?

**Comment by ehendrix23** [comment]
I believe so.

**Comment by FlyingDiver** [comment]
Hmm.  Maybe I'll force change that password and see what happens.

**Comment by FlyingDiver** [comment]
Nope.  Still won't accept it.  I have no idea what the problem is.

**Comment by Goose66** [comment]
These should be the credentials that you use to login to the MyQ mobile app. My app credentials don’t work at MyQ.com, so they evidently can be different. My MyQ mobile app credentials came from my now defunct Liftmaster account.

**Comment by FlyingDiver** [comment]
Ah.  That did work.  Thanks!
