### ISSUE TITLE
API Login Issues 2019-10-18

### ISSUE THREAD

**Issue by brbeaird** [arraylabs/pymyq#25]
It seems MyQ may have made some changes again today. I'm unable to get a successful login response from either the v4 or v5 endpoints. Anyone else having better luck?

V4 Response:
![image](https://user-images.githubusercontent.com/7239272/67121789-f9904d80-f1b1-11e9-977b-75779e6beb32.png)

V5 Response:
![image](https://user-images.githubusercontent.com/7239272/67121806-0745d300-f1b2-11e9-9910-c1bc019b8ed6.png)

**Comment by itzalgd24** [comment]
same here. came home to it not working. multiple errors in my logs. Client error while requesting data from API...yada yada. they changed their API again!

**Comment by txwindsurfer** [comment]
My integration also broke today.

**Comment by brbeaird** [comment]
Correction to my original post: the V5 endpoint IS working if you use the correct AppID. See here for what I posted last time this happened: https://github.com/arraylabs/pymyq/issues/22#issuecomment-518861064

I believe this PR may fix the issue: #23

**Comment by towerhand** [comment]
myq is totally broken for me atm.

**Comment by markolsonjr** [comment]
MyQ integration is also down for me through Home Assistant.

**Comment by brianjamescarter** [comment]
Hello @brbeaird let me know if you are successful with PR #23 . I am getting an invalid username and password error using it, and I am not sure where the web request is getting it wrong.

**Comment by brbeaird** [comment]
I'll give it a shot when I can. Spent most of yesterday updating my SmartThings integration, and it's working again, so I know V5 is still up and running.

Just taking a quick read through the PR, everything seems correct. One thing I've noticed lately is I believe there's just one valid AppID (or brand mapping), so make sure you're using liftmaster as the brand. At some point, we should probably just pull the others out.

I'll take a closer look whenever I get a chance.

**Comment by brianjamescarter** [comment]
Interesting, I am not so sure about the one valid AppID, v5 was working for me using Chamberlain in August. but now it does not work with either Chamberlain or liftmaster. Thanks again @brbeaird for looking into this, since you got it working with smartthings it gives me hope I will find a solution with HomeAssistant

[https://github.com/arraylabs/pymyq/issues/22](url) temporary solution here!

**Comment by bachya** [comment]
@brianjamescarter FYI, in case you're not already aware, we're closing in on a HASS solution in #23. 👍

**Comment by TomBrandt** [comment]
So what is the verdict? Since they won't allow third parties without an paying for it and reverse engineering seems to be a dead issue.

**Comment by brianjamescarter** [comment]
@bachya the good news for me is I am not using HASS.io I am using the Docker install on a linux server, so everything is working again for me. Thank you for all your work!

**Comment by ckhyatt** [comment]
This was working flawlessly and stopped again this afternoon. HA restart does not resolve. I fear Chamberlain is making changes again...
It works in the native MQ app.

**Comment by ckhyatt** [comment]
Error while setting up platform myq
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/src/homeassistant/homeassistant/components/myq/cover.py", line 53, in async_setup_platform
    myq = await login(username, password, websession)
  File "/usr/local/lib/python3.7/site-packages/pymyq/api.py", line 162, in login
    await api.authenticate(username, password)
  File "/usr/local/lib/python3.7/site-packages/pymyq/api.py", line 117, in authenticate
    login_request=True,
  File "/usr/local/lib/python3.7/site-packages/pymyq/api.py", line 85, in request
    data = await resp.json(content_type=None)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1040, in json
    return loads(stripped.decode(encoding))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by codypet** [comment]
I too am having the same issue.
