### ISSUE TITLE
More API Issues

### ISSUE THREAD

**Issue by chipriley** [arraylabs/pymyq#27]
Once again, it seems something has changed.  I restarted my Home Assistant instance this afternoon and my devices are unavailable.  There's a [new issue](https://github.com/home-assistant/home-assistant/issues/28337) in the HA repo regarding this stating that the API is not returning a security token but, rather, a rejection message. 

https://github.com/home-assistant/home-assistant/issues/28337#issuecomment-547641968

**Comment by towerhand** [comment]
Mine started doing that about 24 hrs ago.

**Comment by smrthous** [comment]
Same issue here. 

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "<stdin>", line 3, in main
  File "/usr/local/lib/python3.7/site-packages/pymyq/api.py", line 162, in login
    await api.authenticate(username, password)
  File "/usr/local/lib/python3.7/site-packages/pymyq/api.py", line 117, in authenticate
    login_request=True,
  File "/usr/local/lib/python3.7/site-packages/pymyq/api.py", line 85, in request
    data = await resp.json(content_type=None)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1040, in json
    return loads(stripped.decode(encoding))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)'

**Comment by Bahnburner** [comment]
Same issue here. I dug around a bit but came up mostly empty handed. 

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "<stdin>", line 3, in main
  File "/usr/local/lib/python3.7/site-packages/pymyq/api.py", line 162, in login
    await api.authenticate(username, password)
  File "/usr/local/lib/python3.7/site-packages/pymyq/api.py", line 117, in authenticate
    login_request=True,
  File "/usr/local/lib/python3.7/site-packages/pymyq/api.py", line 85, in request
    data = await resp.json(content_type=None)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1040, in json
    return loads(stripped.decode(encoding))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)```

**Comment by bachya** [comment]
Ugh. 😡

Because the iOS app now does SSL cert pinning, I’m unable to use my traditional methods for sniffing traffic. We will likely need a user who is android app is working to dig in, decompile it and work with us.

**Comment by Bahnburner** [comment]
I'm on android. If you can walk me through what needs to be done, I'd be glad to help. It's been years since I've decompiled an apk.

**Comment by bachya** [comment]
I’m an iOS user, so unfortunately, I won’t be much help there. Basically, what we need is to decompile the most recent version of the app and look around for API calls (URLs that start with `https://api.myqdevice.com/api`). That likely won’t tell us much – we have no clue what they changed – but it will be a starting point.

**Comment by Bahnburner** [comment]
Got it. I've grabbed dex2jar and smali/baksmali and about to pull the APK over ADB. I don't have a rooted device, so depending on how the app is installed it might be futile.

**Comment by bachya** [comment]
Worth a shot. Thanks for attempting!

**Comment by Bahnburner** [comment]
Running into some merge issues with Dex2Jar, building the new version from source. Will report back shortly.

**Comment by brbeaird** [comment]
Has anyone actually reproduced the error in Postman? Manual request is still working for me with the way I call it.

**Comment by brbeaird** [comment]
I think I see it - stop sending the user agent header. Just don't send one at all. That should fix it.

**Comment by Bahnburner** [comment]
> Has anyone actually reproduced the error in Postman? Manual request is still working for me with the way I call it.

Not in postman, but I attempted to manually pull my devices in python in the cli.

**Comment by brbeaird** [comment]
I can submit a PR in just a sec.

**Comment by Bahnburner** [comment]
@brbeaird Well crap. Just got the android apk decompiled. Anyone still need the classes?

**Comment by brbeaird** [comment]
Just pushed a quick PR. Honestly haven't had a chance to test, but I'm about 75% sure it will fix it. Can look deeper into it later if no one has luck with it.

**Comment by Bahnburner** [comment]
> Just pushed a quick PR. Honestly haven't had a chance to test, but I'm about 75% sure it will fix it. Can look deeper into it later if no one has luck with it.

I just manually pulled the changes from your PR to my installation and am restarting hass. I'll let you know how things go.

**Comment by Bahnburner** [comment]
@brbeaird Back up and running after pulling your PR.

**Comment by brg468** [comment]
Same here.

**Comment by kdvlr** [comment]
I am running hass on docker, how do I pull the PR manually ?

**Comment by bachya** [comment]
Good work, @brbeaird!

This can only mean one of two things: they made an API change that requires no user agent at all, or they’ve discovered that the user agent we were using is something they want to block and have shut it off… If it’s the latter, that means they’re actively working to shut off our access.

**Comment by Bahnburner** [comment]
> I am running hass on docker, how do I pull the PR manually ?

```
$ docker exec -it <CONTAINER NAME> bash
# cd /usr/local/lib/python3.7/site-packages/pymyq
# wget -O api.py https://raw.githubusercontent.com/brbeaird/pymyq/dff9fcdd87be2ca4d1507e713d0fc363538f5ec9/pymyq/api.py
# exit
$ docker restart <CONTAINER NAME>
```

**Comment by Bahnburner** [comment]
> Go work, @brbeaird!
> 
> This can only mean one of two things: they made an API change that requires no user agent at all, or they’ve discovered that the user agent we were using is something they want to block and have shut it off… If it’s the latter, that means they’re actively working to shut off our access.

My money would be on the latter.

**Comment by brbeaird** [comment]
I’d say they started blocking the agent, but I don’t think it’s targeted here in particular. The agent being used was also being used by older versions of the mobile app they probably wanted to forcefully discontinue.

**Comment by khicks** [comment]
> Go work, @brbeaird!
> 
> This can only mean one of two things: they made an API change that requires no user agent at all, or they’ve discovered that the user agent we were using is something they want to block and have shut it off… If it’s the latter, that means they’re actively working to shut off our access.

After some trial-and-error, they seem to be looking for the word "Chamberlain" in the user agent to block it. My guess is it's part of their effort to deprecate old apps.

**Comment by towerhand** [comment]
They should just spend their time and resources on a local api for power users.

**Comment by brianjamescarter** [comment]
@Bahnburner , I too run docker so I can run you through the manual process I use.

I download the PR to a location that I have also mapped inside the container, the config folder to be specific. Then I just "docker exec -it [containername] bash" which gets me a cmli inside the container, and manually move the files over to the pymyq directory (will look it up in a bit and edit).

EDIT: location /usr/local/lib/python3.7/site-packages/pymyq

**Comment by brianjamescarter** [comment]
can confirm IT WORKS!!!

Thanks so much @brbeaird

**Comment by brianjamescarter** [comment]
every time this happens, I think to myself "in the morning I am buying a cheap momentary wifi switch and re-doing the garage door to remove the myq..." and every time you fix it before I get to amazon :)

**Comment by Bahnburner** [comment]
> @Bahnburner , I too run docker so I can run you through the manual process I use.
> 
> I download the PR to a location that I have also mapped inside the container, the config folder to be specific. Then I just "docker exec -it [containername] bash" which gets me a cmli inside the container, and manually move the files over to the pymyq directory (will look it up in a bit and edit).
> 
> EDIT: location /usr/local/lib/python3.7/site-packages/pymyq

I think you tagged me by accident. I was providing docker instructions for @kdvlr

**Comment by broyuken** [comment]
There a way for me to fix this on hassio or just wait for the next update to get pushed out?

**Comment by chipriley** [comment]
>There a way for me to fix this on hassio or just wait for the next update to get pushed out?

@broyuken you’ll also need the Portainer add-on to go into the `homeassistant` container via console. It’s a bit convoluted but it can be done by pulling down @brbeaird ‘s PR and overwriting the release files with the files from the PR. I’m on my phone right now so it’s a bit much to type out. I’m sure someone else will walk you through it if you’re comfortable with the above. I did it a few days ago when it broke the first time. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kdvlr** [comment]
Thanks @Bahnburner - Your instructions worked like a charm!

**Comment by broyuken** [comment]
I have ssh access to the box but I can’t find phmyq anywhere on the system. Not sure where these files are located for a hassio install.

**Comment by ehendrix23** [comment]
I just pulled in the request and uploaded to PyPI as version 2.0.1. @bachya, any chance you can get home assistant updated to use version 2.0.1? I do not have development for home assistant setup on this PC anymore.

**Comment by bachya** [comment]
Will do!

**Comment by brianjamescarter** [comment]
Broyuken, seems you might have a typo, look for pymyq . In my docker it is located here /usr/local/lib/python3.7/site-packages/pymyq
________________________________

**Comment by broyuken** [comment]
I typed it right on the box, wrong here. I’m not running docker, I’m running the hassio image on a vm.

**Comment by bachya** [comment]
FYI, a HASS PR has been opened: https://github.com/home-assistant/home-assistant/pull/28348

**Comment by Bahnburner** [comment]
> I typed it right on the box, wrong here. I’m not running docker, I’m running the hassio image on a vm.

You should be able to find it with `# find / -name pymyq`

**Comment by broyuken** [comment]
I figured I would be able to but I can't

core-ssh:~# find / -name pymyq
core-ssh:~#

**Comment by Bahnburner** [comment]
Did you dive into the hassio container before searching? Hassio is set up in a similar manner to docker. Pymyq won't be running on the VM, but will instead be inside a container on the VM.

**Comment by broyuken** [comment]
I don’t know how to do that, I have 0 docker experience lol

Looking at the above example, what’s the container name?

**Comment by Bahnburner** [comment]
> I don’t know how to do that, I have 0 docker experience lol
> 
> Looking at the above example, what’s the container name?

Unfortunately, I don't have any experience with or access to a hass.io setup. Unless someone else is able to assist, you may have to wait for a hass hotfix release.

**Comment by garyak** [comment]
Container name in my 0.100.3 hassio installation is homeassistant.

**Comment by broyuken** [comment]
core-ssh:~# docker exec -it homeassistant /bin/bash
-bash: docker: command not found
core-ssh:~#

**Comment by Bahnburner** [comment]
Yeah, those commands won't work since you don't have docker installed and are not running a docker container.

**Comment by broyuken** [comment]
thats what I thought, so is there a way to access these files on a hassio install using the vm image from the official website? It's running on the official alpine linux distro

**Comment by jsenurquhart** [comment]
i'm also running hass and wondering the same as broyuken.

**Comment by Bahnburner** [comment]
> thats what I thought, so is there a way to access these files on a hassio install using the vm image from the official website? It's running on the official alpine linux distro

Based on @chipriley 's response earlier, you'll need the portainer add-on in hass.io to alter the container. 



> i'm also running hass and wondering the same as broyuken.

Are you running Hass or Hass.io?

**Comment by jsenurquhart** [comment]
@Bahnburner sorry for confusion .. I'm running HassOS 2.12

**Comment by chipriley** [comment]
> > There a way for me to fix this on hassio or just wait for the next update to get pushed out?
> 
> @broyuken you’ll also need the Portainer add-on to go into the `homeassistant` container via console. It’s a bit convoluted but it can be done by pulling down @brbeaird ‘s PR and overwriting the release files with the files from the PR. I’m on my phone right now so it’s a bit much to type out. I’m sure someone else will walk you through it if you’re comfortable with the above. I did it a few days ago when it broke the first time.
> 
> Sent with [GitHawk](http://githawk.com)

So, to clarify my previous reply to @broyuken last night:  In order to modify the `pymyq` files on a Hass.io install, you'll either need some manual setup to be able to ssh into the `homeassistant` container or, _much easier in my experience_, install the [Portainer Community Add-on](https://github.com/hassio-addons/addon-portainer) so that you can use its console access to get command line inside the `homeassistant` container.  

**CAVEAT:  Portainer gives you a lot of access/power to make changes to Hass.io.  If you aren't comfortable with that, just wait for an update.  I'm not responsible for bricking your HA.**

Once you have Portainer set up (which includes turning off Protected mode), either click on the Portainer sidebar icon (if you turned that on) or access it via a browser at whatever port you set up. From the main screen:

1. Click Containers in the Portainer sidebar (not the HA sidebar).
2. Click on `homeassistant` in the Name column.
3. Under Container status, click on `>_Console`.
4. Click the Connect button.

You know have cli access to the `homeassistant` container.  The `pymyq` directory is located at `/usr/local/lib/python3.7/site-packages/pymyq`.  I wouldn't change anything in that directory until you've backed it up.  I don't have the time to cover the Linux commands for copying the files, checking out @brbeaird 's PR, or other cli tasks right now.  Hopefully, that gets everyone on their way.  I haven't actually updated my HA, yet, either.  You may need to edit the `cover.py` component for myq, also, which is located in `/usr/src/homeassistant/homeassistant/components/myq`.

**Comment by mickeyschwab** [comment]
Following up on @chipriley's helpful comment, now that this release is published in pip, you only need to update `/usr/src/homeassistant/homeassistant/components/myq/manifest.json` to reflect the 2.0.1 release and restart HASS.

```
bash-5.0# cat /usr/src/homeassistant/homeassistant/components/myq/manifest.json
{
  "domain": "myq",
  "name": "Myq",
  "documentation": "https://www.home-assistant.io/integrations/myq",
  "requirements": [
    "pymyq==2.0.1"
  ],
  "dependencies": [],
  "codeowners": []
}
```

**Comment by chipriley** [comment]
>Following up on @chipriley's helpful comment, now that this release is published in pip, you only need to update `/usr/src/homeassistant/homeassistant/components/myq/manifest.json` to reflect the 2.0.1 release and restart HASS. ...

@mickeyschwab **nice!**

**EDIT: Confirmed!**🎉

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by CarterBrehm** [comment]
@mickeyschwab, I'm trying to recreate your results in my virtualenv, but changing `/opt/homeassistant/lib/python3.6/site-packages/homeassistant/components/myq/manifest.json` to 2.0.1 doesn't seem to affect the process of upgrading Home Assistant. Is there a different process?

**Comment by Bahnburner** [comment]
The lazy way would be to simply `pip install pymyq --upgrade` after activating the venv. This will update the installed version to 2.0.1 which home assistant should use without complaint.

**Comment by mickeyschwab** [comment]
> The lazy way would be to simply `pip install pymyq --upgrade` after activating the venv. This will update the installed version to 2.0.1 which home assistant should use without complaint.

This is the correct way if you're not running inside Docker, should have mentioned it in my comment. I don't even think it's lazy given HASS will release an update this week most likely with this fix :+1:

**Comment by CarterBrehm** [comment]
I'm confused. I stop the service, then run `pip show pymyq` it returns:
```
(homeassistant) homeassistant@ares:/opt/homeassistant$ pip show pymyq
Name: pymyq
Version: 2.0.0
```
So I run the upgrade command, and it looks like the upgrade works fine:
```
(homeassistant) homeassistant@ares:/opt/homeassistant$ pip install pymyq --upgrade
Collecting pymyq
  Using cached https://files.pythonhosted.org/packages/a8/c5/9387033bb8696ac08489e041bbf04a51f547e0b5fd487a156f26fcf604f5/pymyq-2.0.1-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: aiohttp in ./lib/python3.6/site-packages (from pymyq) (3.6.1)
Requirement already satisfied, skipping upgrade: aiodns in ./lib/python3.6/site-packages (from pymyq) (2.0.0)
Requirement already satisfied, skipping upgrade: async-timeout in ./lib/python3.6/site-packages (from pymyq) (3.0.1)
Requirement already satisfied, skipping upgrade: chardet<4.0,>=2.0 in ./lib/python3.6/site-packages (from aiohttp->pymyq) (3.0.4)
Requirement already satisfied, skipping upgrade: multidict<5.0,>=4.5 in ./lib/python3.6/site-packages (from aiohttp->pymyq) (4.5.2)
Requirement already satisfied, skipping upgrade: typing-extensions>=3.6.5; python_version < "3.7" in ./lib/python3.6/site-packages (from aiohttp->pymyq) (3.7.4)
Requirement already satisfied, skipping upgrade: idna-ssl>=1.0; python_version < "3.7" in ./lib/python3.6/site-packages (from aiohttp->pymyq) (1.1.0)
Requirement already satisfied, skipping upgrade: yarl<2.0,>=1.0 in ./lib/python3.6/site-packages (from aiohttp->pymyq) (1.3.0)
Requirement already satisfied, skipping upgrade: attrs>=17.3.0 in ./lib/python3.6/site-packages (from aiohttp->pymyq) (19.2.0)
Requirement already satisfied, skipping upgrade: typing; python_version < "3.7" in ./lib/python3.6/site-packages (from aiodns->pymyq) (3.7.4.1)
Requirement already satisfied, skipping upgrade: pycares>=3.0.0 in ./lib/python3.6/site-packages (from aiodns->pymyq) (3.0.0)
Requirement already satisfied, skipping upgrade: idna>=2.0 in ./lib/python3.6/site-packages (from idna-ssl>=1.0; python_version < "3.7"->aiohttp->pymyq) (2.8)
Requirement already satisfied, skipping upgrade: cffi>=1.5.0 in ./lib/python3.6/site-packages (from pycares>=3.0.0->aiodns->pymyq) (1.12.3)
Requirement already satisfied, skipping upgrade: pycparser in ./lib/python3.6/site-packages (from cffi>=1.5.0->pycares>=3.0.0->aiodns->pymyq) (2.19)
Installing collected packages: pymyq
  Found existing installation: pymyq 2.0.0
    Uninstalling pymyq-2.0.0:
      Successfully uninstalled pymyq-2.0.0
Successfully installed pymyq-2.0.1
```
`pip show pymyq` also shows the version as `2.0.1`. So I go to start the service back up, and immediately after, running `pymyq` gives: 
```
(homeassistant) homeassistant@ares:/opt/homeassistant$ pip show pymyq
Name: pymyq
Version: 2.0.0
```
What gives? Does Hass auto update on start or something?

**Comment by mickeyschwab** [comment]
@CarterBrehm I don't have a standard install like you do but based on home-assistant/home-assistant#28348 is there a manifest file inside of `/opt/homeassistant/components/myq`?

**Comment by jsenurquhart** [comment]
Wow.. man you guys work wonderfully as a team and contribute more knowledge than you may actually be aware of. 

Too many names to mention .. so 

Thank you all!

**Comment by broyuken** [comment]
There was a home assistant update last night, looks like this didn’t make the cut?

**Comment by chipriley** [comment]
>There was a home assistant update last night, looks like this didn’t make the cut?

@broyuken it’s in 0.101.1 that [just popped](https://github.com/home-assistant/home-assistant/pull/28348).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by B-Kramer** [comment]
```
ha update --version 0.101.1
```
from the hassio terminal if you don't see the update yet...

**Comment by broyuken** [comment]
Hasn’t made it to the hassio update GUI yet, I fixed it with portainer the other day worked like a charm

Edit: Just checked again and the update is there now.
