### ISSUE TITLE
Add Light support

### ISSUE THREAD

**Issue by SConaway** [arraylabs/pymyq#3]
Add Light support to control lights in addition to Garage Doors.

**Comment by SConaway** [comment]
Am Currently working on this.

**Comment by petewill** [comment]
I would also love to see light support.  I see a couple of PRs with light support but they haven't been committed.  Is there any way we can get one committed so lights can be supported in Home Assistant?  Unfortunately I don't know enough about HA to hack something in on my own.

**Comment by brbeaird** [comment]
FYI - the MyQ V5 command options for lights is "turnon" and "turnoff." Wasn't exactly easy to find, but it's buried in the Android apk if anyone ever wants to go digging for it.

**Comment by chrismcneil** [comment]
Ohh please add lights! I have some automations in mind for the lights :)

**Comment by brbeaird** [comment]
To be clear, this is not the lights in the doors themselves - it's the separate "lamp modules" they sell.

**Comment by chrismcneil** [comment]
Awe too bad! I was hoping to turn on the lights in the garage when my door sensor noticed the door open.. The wall button does have a motion sensor and a light button so I was hopeful it was exposed somehow in the apis..

**Comment by ehendrix23** [comment]
Version 3.0.0 will have support for lights. Currently working on it together with V6 API.

**Comment by SConaway** [comment]
@ehendrix23 let me know if there's anything I can do to help and when it's ready for testing!

You might want to close #13 and #14, by the way.

**Comment by ehendrix23** [comment]
Support added in v3.0.0
