### ISSUE TITLE
Update PyPi with latest version?

### ISSUE THREAD

**Issue by broox** [arraylabs/pymyq#5]
The latest version of PyMyQ on [PyPi](https://pypi.python.org/pypi/pymyq/) is v0.0.8. It'd be great to get the bug fixes from v0.0.9 and v0.0.10 out there!

**Comment by arraylabs** [comment]
I agree, just haven't had enough free time to figure out the pypi stuff again. Takes 10 seconds to setup a build in github, but last time I did pypi I had to setup an entire VM in order to get things packaged. Maybe I did it the hard way, and have missed an easier method.

**Comment by broox** [comment]
I'd be happy to help, if you'd like it.

If I remember correctly, these are the main steps (you've already done the first 3):
- [x] bump version numbers in setup.py
- [x] push to master
- [x] tag a matching release
- [ ] python setup.py sdist upload -r pypi

**Comment by broox** [comment]
Hi, @arraylabs, if getting your VM setup to distribute this out to PyPi is a hassle, I have no problem pushing the latest version out to PyPi, if you'd like.

You'd simply have to add me (`broox`) as a contributor or maintainer here: https://pypi.python.org/pypi?:action=role_form&package_name=pymyq

And then, I can just run the command above (`python3 setup.py sdist upload -r pypi`) to push the latest release that you've defined in [setup.py](https://github.com/arraylabs/pymyq/blob/master/setup.py])

I just tested this out on the test pypi package index (`python3 setup.py sdist upload -r pypitest`) and it published your latest release just fine: https://testpypi.python.org/pypi/pymyq/

I was gonna make you the owner of the test one, but I didn't see that you have an account there (for some reason, pypi and testpypi use different accounts). Let me know if you do and I'll make you the owner of the test one as well.

**Comment by aaronwolen** [comment]
Yes, please! Running 0.0.10 fixes the MyQ errors that were regularly popping up in my HA log.

**Comment by jwater7** [comment]
@arraylabs - Please let @broox (if he’s still willing) push the latest version to pypi to fix the login timeout issue for Home Assistant.  Thanks

**Comment by arraylabs** [comment]
@jwater7, @aaronwolen I will get .11 pushed out to pypi in the next couple days. Thanks for the reminder and I apoligize for being away, real life has really pushed me away from fun things for quite a while now.

**Comment by jwater7** [comment]
Great news, thanks!

**Comment by arraylabs** [comment]
It's been published and PR submitted for HA.

**Comment by jwater7** [comment]
Great!  Now it’s up to the HA team for https://github.com/home-assistant/home-assistant/pull/14947 to resolve https://github.com/home-assistant/home-assistant/issues/14903

I think this issue can be resolved, thanks!
