### ISSUE TITLE
MyQ issue

### ISSUE THREAD

**Issue by Pzharyuk** [arraylabs/pymyq#55]
It looks like MyQ is broke again. I'm getting unexpected error when trying to login again.

**Comment by dseven** [comment]
Dup of https://github.com/arraylabs/pymyq/pull/54

**Comment by BreakTheBonds** [comment]
I just off of the phone with Liftmaster Support. They stated that the latest updates to their system will no longer allow connections to their API from third party applications that they have not approved as compatible. He stated that in order for devices to connect, that they must agree to their new TOS as a "partner". I would not be surprised if this wasn't pushed by Amazon, as their Alexa and Ring products love to take control by limiting the competition.

**Comment by ehendrix23** [comment]
2.0.12 fixes it for now

**Comment by whreams** [comment]
> I just off of the phone with Liftmaster Support. They stated that the latest updates to their system will no longer allow connections to their API from third party applications that they have not approved as compatible. He stated that in order for devices to connect, that they must agree to their new TOS as a "partner". I would not be surprised if this wasn't pushed by Amazon, as their Alexa and Ring products love to take control by limiting the competition.

I do have a registered LiftMaster MyQ hub, but I use the HB plugin for control.  I wonder if eMails that are registered are allowed through using the plugin - while others that are "hub-less" are getting blocked?

**Comment by matellis** [comment]
> > I just off of the phone with Liftmaster Support. They stated that the latest updates to their system will no longer allow connections to their API from third party applications that they have not approved as compatible. He stated that in order for devices to connect, that they must agree to their new TOS as a "partner". I would not be surprised if this wasn't pushed by Amazon, as their Alexa and Ring products love to take control by limiting the competition.
> 
> I do have a registered LiftMaster MyQ hub, but I use the HB plugin for control. I wonder if eMails that are registered are allowed through using the plugin - while others that are "hub-less" are getting blocked?

This would fine if their HomeKit product actually worked. Very frustrating.

**Comment by iRayanKhan** [comment]
@matellis my opener has a HomeKit code on it, but it's blocked without a hub.

**Comment by matellis** [comment]
I bought a hub and installed it. It was unable to connect to the web no matter what I did. I even setup a fresh network with just the hub on it and it still didn’t work. Returned it. Would gladly use it if I could make it work.

**Comment by hjdhjd** [comment]
@matellis PM me on the Homebridge Discord. I am reasonably sure I can point you in the right direction on the hub itself. :smile:

**Comment by hjdhjd** [comment]
@whreams I have a physical hub, it doesn’t make a difference. Something meaningful has changed in the way the API authenticates the client. What that something is, we need someone with a rooted Android device, bypass certificate pinning, and MITM the myQ app and post the traffic so we can figure out where to go from here.

The other (easier) option is for someone, somewhere, to have a working user agent sequence...but that’s a short-term fix.

**Comment by Landshark77** [comment]
> The other (easier) option is for someone, somewhere, to have a working user agent sequence...but that’s a short-term fix.
FWIW, I switched over to HA in the meantime and it's working there after I changed the DEFAULT_USER_AGENT to "pymyq".  If there's something I can pull from my config on HA let me know and I'll see if I can pull it.

**Comment by hjdhjd** [comment]
I tried pymyq as well...nope. This game of cat and mouse just gets more annoying...as if they don’t have something better to do with their time.

**Comment by matellis** [comment]
Like making their HomeKit integration work….

**Comment by hjdhjd** [comment]
@matellis It does work...sort of. As I said above, PM me on the Homebridge Discord...might be able to help on that front, if you have the hardware hub. :smile:
