### ISSUE TITLE
Bump multidict to version >=4.5 for requirements.txt

### ISSUE THREAD

**Issue by evanugarte** [arraylabs/pymyq#69]
This is an amazing project! The code is written very elegantly too. I noticed when installing `requirements.txt` I was met with this warning:

```
ERROR: aiohttp 3.7.3 has requirement multidict<7.0,>=4.5, but you'll have multidict 4.4.2 which is incompatible.
```

When I changed `multidict`'s version to >=4.5, the issue went away and the demo ran just fine. Could I open a PR to bump the version? I also saw #61, maybe dependabot will handle this eventually.

**Comment by dseven** [comment]
I don't see any direct use of multidict in the pymyq code. If it's just for aiohttp, maybe the requirements.txt entry can be removed (and let aiohttp deal with the dependency)?
