### ISSUE TITLE
API v6 is worked out

### ISSUE THREAD

**Issue by bdraco** [arraylabs/pymyq#78]
hjdhjd has done a great job of documenting what is going on with the new api here: https://github.com/hjdhjd/homebridge-myq/blob/master/src/myq-api.ts#L21

Its likely the v5 update used here is going to disappear any day.

**Comment by bdraco** [comment]
To make this work in Home Assistant, we would likely need to proxy the oauth login and capture the token that come back so we can avoid web scraping

**Comment by GaryOkie** [comment]
Nick - hjdhjd did indeed do a great job working out the V6 OAuth and documenting it.    He collaborated with @ehendrix23 who has also done some great work and has already implemented an update to both the HA myq integration and pymyq.   Several of us have been testing it, and so far, it's working great!

I suppose any day now Erik will submit a PR for you to review.

Please see #67 for the update comments.

**Comment by bdraco** [comment]
Thanks. Missed there was an existing issue.

Closing this one
