### ISSUE TITLE
TypeError on rpi, working on windows test enviroment

### ISSUE THREAD

**Issue by rishipudipeddi** [arraylabs/pymyq#80]
On a windows 10 visual studio code debugging environment, the module works as expected but running the same code on a raspberry pi with all dependencies installed produces error
`/home/pi/.local/lib/python3.7/site-packages/pymyq/api.py:452: RuntimeWarning: coroutine 'API._authenticate' was never awaited
  self._authenticate(), name="MyQ_Authenticate"
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "garage.py", line 12, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "garage.py", line 9, in main
    myq = await pymyq.login(creds.email, creds.password, websession)
  File "/home/pi/.local/lib/python3.7/site-packages/pymyq/api.py", line 648, in login
    await api.authenticate(wait=True)
  File "/home/pi/.local/lib/python3.7/site-packages/pymyq/api.py", line 452, in authenticate
    self._authenticate(), name="MyQ_Authenticate"
TypeError: create_task() got an unexpected keyword argument 'name'`

Only difference in environments that I can think of is on my windows 10 machine, the script uses python 3.8.5 while on the raspberry pi it uses 3.7.3

**Comment by ehendrix23** [comment]
Python 3.8 or higher is required. You’re on Python 3.7.

**Comment by rishipudipeddi** [comment]
@ehendrix23 commented to say that reason i didn't realize that was because on the pypi page it states python version as >= 3.5.3. Might want to change that
