### ISSUE TITLE
Ownership of pymyq in Pypi

### ISSUE THREAD

**Issue by ehendrix23** [arraylabs/pymyq#82]
@arraylabs,

Seems that I've pretty much have taken over development of pymyq now. :-)

Been thinking of creating a fork of yours to mine and then continue development in my own fork, pretty much making it the repository.

I can also take ownership of pymyq in PyPi. If you want to transfer it over to me?

Thx.

**Comment by glyph** [comment]
@ehendrix23 I notice that somebody has done a release since you posted this comment — is this still relevant?

**Comment by ehendrix23** [comment]
I was given access to post releases to pypi long time ago for pymyq. But was hoping to be able to take complete ownership and then use my fork as the actual source.
Leaving it open in the hopes @arraylabs shows up again sometime in the future. :-)

**Comment by arraylabs** [comment]
@ehendrix23 I'm here, I'm certainly open to moving anything or all over to you. I don't have the device any longer so it's hard to contribute unfortunately. If you could point me in the right direction of where/what you need I can work with you to get things moved/transitioned.

**Comment by arraylabs** [comment]
@ehendrix23 I've added you as an owner on pypi. If you need anything else let me know.

**Comment by ehendrix23** [comment]
Thx!
