### ISSUE TITLE
error every 30 seconds or so in HA

### ISSUE THREAD

**Issue by jes1417** [arraylabs/pymyq#86]
I am seeing an error very frequently in my HA logs and it seems the api is seeing an unknown device, I am wondering if it is my Lockitron Bolt I have paired with my MyQ hub

```
Logger: pymyq.api
Source: /usr/local/lib/python3.8/site-packages/pymyq/api.py:591
First occurred: 12:31:25 AM (15 occurrences)
Last logged: 12:35:00 AM

Unknown device family locks
```

**Comment by ehendrix23** [comment]
It would be :-)

Can you provide me with your detailed config output? I changed the coding right now so it will be classified as another device and still be added as a device. Just won't be able to operate it. But I want to confirm this works based on the configuration received.

Just run:
```python3 -m aioharmony --harmony_ip <your IP> show_detailed_config```

Thx!

**Comment by jes1417** [comment]
> Just run:
> `python3 -m aioharmony --harmony_ip <your IP> show_detailed_config`

Im a little confused, it looks like this command pulls a harmony config but I was talking about my MyQ hub, it didnt work using the IP of MyQ which I kind of expected 🤪  it did pull my harmony config though when I changed the IP 😄

**Comment by haffi78** [comment]
Are you working on integrating the lockitron Via MyQ ? if so I have one if you need testing. Would love to get that back to work. I am also getting the errors.

2021-03-30 21:49:23 WARNING (MainThread) [pymyq.api] Unknown device family locks
2021-03-30 21:49:39 WARNING (MainThread) [pymyq.api] Unknown device family locks
2021-03-30 21:49:55 WARNING (MainThread) [pymyq.api] Unknown device family locks
2021-03-30 21:50:11 WARNING (MainThread) [pymyq.api] Unknown device family locks
2021-03-30 21:50:27 WARNING (MainThread) [pymyq.api] Unknown device family locks

**Comment by jes1417** [comment]
still seeing these issues on 2021.4.6

```
Logger: pymyq.api
Source: /usr/local/lib/python3.8/site-packages/pymyq/api.py:591
First occurred: April 25, 2021, 11:36:13 PM (107 occurrences)
Last logged: 12:03:29 AM

Unknown device family locks
```

**Comment by jes1417** [comment]
This issue is so noisy I had to disable it.

**Comment by jes1417** [comment]
Still an issue I just set logging to error so I forgot about it but it is still as noisy as ever. 

```
Logger: pymyq.api
Source: /usr/local/lib/python3.9/site-packages/pymyq/api.py:591
First occurred: 10:26:59 PM (266 occurrences)
Last logged: 11:33:17 PM

Unknown device family locks
```

**Comment by haffi78** [comment]
Anyone planing on integrating the lock ? I am willing to help if needed , but kinda don't know where to start, would love to be able to get mynlockitron back

**Comment by ehendrix23** [comment]
> Still an issue I just set logging to error so I forgot about it but it is still as noisy as ever.
> 
> ```
> Logger: pymyq.api
> Source: /usr/local/lib/python3.9/site-packages/pymyq/api.py:591
> First occurred: 10:26:59 PM (266 occurrences)
> Last logged: 11:33:17 PM
> 
> Unknown device family locks
> ```

Can you try out the custom HACS component. It is the same as the one in HASS but uses latest beta version of myq.

Install HACS custom component (if not already there) and then deploy the component using following link:
https://github.com/ehendrix23/hass_myq

**Comment by ehendrix23** [comment]
> Anyone planing on integrating the lock ? I am willing to help if needed , but kinda don't know where to start, would love to be able to get mynlockitron back

No plans. Do not have/know the API for this.

**Comment by haffi78** [comment]
Is it not just a matter of defing it, probly uses same open close as the cover/garage doors or ?

**Comment by ehendrix23** [comment]
No, most likely it is going to be different API calls and different information received back.

**Comment by ehendrix23** [comment]
Closing this issue as it should have been resolved with latest releases.
