### ISSUE TITLE
Device Online: False

### ISSUE THREAD

**Issue by 88gts** [arraylabs/pymyq#89]
Is anyone else seeing issues with invalid online states?  I can access through the MyQ app and through HomeKit with no issues but when I try and use the script its reporting that all devices are offline.  This just started happening recently.  I rebooted the Gateway and also the Hub with no change in response.

INFO:root:---------
INFO:root:Device 1: First
INFO:root:Device Online: False
INFO:root:Device Family: garagedoor
INFO:root:Device Platform: myq
INFO:root:Device Type: virtualgaragedooropener
INFO:root:Firmware Version: None
INFO:root:Open Allowed: True
INFO:root:Close Allowed: True
INFO:root:Current State: closed
INFO:root:---------
INFO:root:Device 2: Home
INFO:root:Device Online: False
INFO:root:Parent Device ID: None
INFO:root:Device Family: gateway
INFO:root:Device Platform: myq
INFO:root:Device Type: ethernetgateway
INFO:root:Firmware Version: 1.6
INFO:root:Open Allowed: False
INFO:root:Close Allowed: False
INFO:root:Current State: None
INFO:root:---------
INFO:root:Device 3: Second
INFO:root:Device Online: False
INFO:root:Device Family: garagedoor
INFO:root:Device Platform: myq
INFO:root:Device Type: virtualgaragedooropener
INFO:root:Firmware Version: None
INFO:root:Open Allowed: True
INFO:root:Close Allowed: True
INFO:root:Current State: closed

**Comment by dseven** [comment]
What is "the script"? and what version of pymyq are you trying to use?

**Comment by 88gts** [comment]
Good call, I thought I was on something more recent, but I just updated to 3.0.4.  I think something is broken because now I am getting the following when just implementing the test script in the readme to get all devices associated with an account...


```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    import pymyq
  File "/var/www/scripts/notify/pymyq/pymyq/__init__.py", line 2, in <module>
    from .api import login  # noqa
  File "/var/www/scripts/notify/pymyq/pymyq/api.py", line 32, in <module>
    from .request import MyQRequest, REQUEST_METHODS
  File "<fstring>", line 1
    (await resp.text())
              ^
SyntaxError: invalid syntax
```

**Comment by 88gts** [comment]
Likely due to using Py3.6, will try to upgrade.

**Comment by 88gts** [comment]
there must have been a server side change to invalidate my old 6mo code, all good on 3.8 and the latest branch. thanks!
