### ISSUE TITLE
mqtt access for pymyq

### ISSUE THREAD

**Issue by flavio-fernandes** [arraylabs/pymyq#91]
Thank you for this awesome project! I find it to be a great pure python implementation for controlling my garage doors. At first I was planning to use [Homebridge myQ](https://github.com/hjdhjd/homebridge-myq) but decided it was not "pythonic" enough for me. The install part of the documentation is not very friendly for a Nodejs newbie. I could not make it work.

What I need is a way to connect this project to MQTT and since I do not use [Home Assistant](https://www.home-assistant.io/), the [plugin](https://www.home-assistant.io/integrations/myq/) was too heavy handed for me. So just I created one:

https://github.com/flavio-fernandes/mqtt2garage

I hope that can be useful to other folks too.

Thanks again,

-- flaviof

**Comment by ehendrix23** [comment]
Thx for doing this. Will be closing this issue now but anyone looking for MQTT in this repository for sure will find your post.
