### ISSUE TITLE
Embedded (C/C++) port?

### ISSUE THREAD

**Issue by jshep321** [arraylabs/pymyq#94]
Hi,
Any insight or thoughts on porting this functionality to allow for execution on an embedded arduino, esp32, etc?   I haven't looked through the code but I assume the only "heavy lifting" parts would be https encryption, which works fine on these types of MCUs?
Thanks!

**Comment by ehendrix23** [comment]
Definitely not something I would be doing, but the code is open source so anyone can review and do a port.
Only other option would be to compile the python but not sure if it is available for the platforms you're requesting.
