### ISSUE TITLE
Devices unavailable "500 - Internal Server Error"

### ISSUE THREAD

**Issue by squirtbrnr** [arraylabs/pymyq#96]
EDIT:  This may not be an issue with the pymyq library or Home Assistant component.  I'm reporting it in case others are also unable to control their MyQ openers.

As of approximately 18:57 UTC on 4/19, my two MyQ openers are unavailable.

The error log in Home Assistant is:
```
2021-04-19 13:57:22 ERROR (MainThread) [homeassistant.components.myq] Error fetching myq devices data: Error requesting data from https://devices.myq-cloud.com/api/v5.2/Accounts/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/Devices: 500 - Internal Server Error
```

Going to that API call in another browser returns the following:
```
{
    "ReturnCode": "-99",
    "ErrorMessage": "please contact customer care, supportID: xxxxxxxxxxxxxxxxxxxx",
    "CorrelationId": ""
}
```

I removed the account from the API link as well as the supportID number.

![image](https://user-images.githubusercontent.com/35356217/115292227-4fcdac00-a11b-11eb-955e-64cfe7522056.png)

**Comment by dseven** [comment]
Getting 500's here too. Hopefully it's just a glitch .. let's wait a bit and see.....

**Comment by squirtbrnr** [comment]
MyQ is stating there is an outage with their server.

![image](https://user-images.githubusercontent.com/35356217/115294434-35490200-a11e-11eb-8291-2ba5c74e349e.png)
